
# This workflow will build a docker container, publish it to IBM Container Registry, and deploy it to IKS when a release is created
#
# To configure this workflow:
#
# 1. Ensure that your repository contains a Dockerfile
# 2. Setup secrets in your repository by going to settings: Create ICR_NAMESPACE and IBM_CLOUD_API_KEY
# 3. Change the values for the IBM_CLOUD_REGION, REGISTRY_HOSTNAME, IMAGE_NAME, IKS_CLUSTER, DEPLOYMENT_NAME, and PORT

name: Hello k8s App

on: 
  push:
    branches:
      - main
    paths:
      - 'hello-kube-app/**'
  workflow_dispatch:
    name:
      description: 'Test scenario tags' 

jobs:
  setup-build-publish-deploy:
    name: Development Build & Deploy Hello-Kube
    runs-on: ubuntu-latest
    environment: development
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Starting Build & Push  Status Slack Notification
      uses: ravsamhq/notify-slack-action@v2
      if: always()
      with:
        status: ${{ job.status }}
        token: ${{ secrets.GHTOKEN }}
        notification_title: "Starting Build Kube-Hello"
        notify_when: "failure, success, warning"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.WEBHOOK }}

    - name: Generate build number
      uses: einaregilsson/build-number@v3
      with:
        token: ${{ secrets.GHTOKENCLASSIC }}  

    - name: Print new build number
      run: echo "Build number is $BUILD_NUMBER"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # Build the Docker image
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: hello-kube
        IMAGE_TAG: 5
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./hello-kube-app1/
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG