name: "When updates are pushed or the defined schedule is triggered, scan the container and application for vulnerabilities"

on:

  push:

  schedule:
    - cron: '0 0 * * *'

jobs:

  scan-and-report-vulnerabilities:
    
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3
  
    - name: Run Trivy vulnerability scanner
      env:
        ECR_REGISTRY: vuln-checker.de
        ECR_REPOSITORY: hello-kube
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./hello-kube-app1
        curl -L https://github.com/aquasecurity/trivy/releases/download/v0.19.2/trivy_0.19.2_Linux-64bit.tar.gz | tar xvzf - contrib trivy
        chmod 755 trivy
        mv trivy /usr/local/bin/trivy
        trivy image --format template --template "@contrib/sarif.tpl" --output trivy-results.sarif $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    
    - name: Upload container results to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: trivy-results.sarif